### ISSUE TITLE
Use `System.Storage_Elements.Storage_Array` instead of `Ada.Streams.Stream_Element_Array`

### ISSUE THREAD

**Issue by Fabien-Chouteau** [stcarrez/resource-embedder#1]
Great project @stcarrez !

https://github.com/stcarrez/resource-embedder/blob/cf491d2c73c90daace4e39dbc221a4b4990a349f/src/are-generator-ada2012.adb#L117

The package `Ada.Streams.Stream_Element_Array` is not available in all Ada run-times (in particular the ZFP for embedded targets), so using [`System.Storage_Elements.Storage_Array`](https://www.adaic.org/resources/add_content/standards/12aarm/html/AA-13-7-1.html) would make the generated code more usable/portable.

**Comment by stcarrez** [comment]
No, I don't think so because all the `Ada.Streams` operations require the `Stream_Element_Array` type.

We need more flexibility for the choice of the content type.

There is this `--no-type-declaration` option that you can use when you provide your own type in a parent
package but I realize it does not solve your issue.

**Comment by Fabien-Chouteau** [comment]
I see. In what ues case would that be a problem?

Because you can also stream Storage_Array:
```ada
with System.Storage_Elements; use System.Storage_Elements;
with Ada.Text_IO;
with Ada.Text_IO.Text_Streams;
use  Ada.Text_IO;

procedure Test is
   Buffer : constant System.Storage_Elements.Storage_Array :=
     (ASCII.LC_A'Enum_Rep,
      ASCII.LC_B'Enum_Rep,
      ASCII.LC_C'Enum_Rep,
      ASCII.LC_D'Enum_Rep);
begin
   Storage_Array'Write (Text_Streams.Stream (Current_Output), Buffer);
end Test;
```

**Comment by stcarrez** [comment]
This example is specific and addresses only the use of `'Write` but there are other cases where you may
need to give standard Ada type to an operation that require it. I have plenty of these in my projects and they
are not replaceable by writing to a stream.

**Comment by stcarrez** [comment]
I've fixed the Ada generator so that it better handles the `type` declaration in the package XML file.

By default it continues using the `Ada.Streams.Stream_Element_Array` because this is a most standard type.

But if you write the following:

```XML
<package>
  <resource name='Resources.Help'
            format='binary'
            type='access constant System.Storage_Elements.Storage_Array'>
    <install mode='copy'>
      <fileset dir="help">
        <include name="**/*.txt"/>
      </fileset>
    </install>
  </resource>
  ...
</package>
```

It generates:

```Ada
with System.Storage_Elements;
package Resources.Help is

   type Content_Access is access constant System.Storage_Elements.Storage_Array;

   type Name_Access is access constant String;

   type Name_Array is array (Natural range <>) of Name_Access;

   Names : constant Name_Array;

   --  Returns the data stream with the given name or null.
   function Get_Content (Name : String) return
      access constant System.Storage_Elements.Storage_Array;

private
...
end Resources.Help;
```


It should work with any `access constant X` type, so you may use your own type as long as it is compatible with the generated content code which looks like:

```Ada
   C_0 : aliased constant System.Storage_Elements.Storage_Array :=
     (99, 111, 110, 102, 105, 103, 58, 32, 103, 101, 116, 32, 111, 114, 32, 115, 101, 116, 32, 103, 108,
      111, 98, 97, 108, 32, 111, 112, 116, 105, 111, 110, 115, 10, 10, 85, 115, 97, 103, 101, 58,
...
```
